baseURL = "https://astro.uvic.ca/~dboyea/"
languageCode = "en-us"
title = "Daniel Boyea"
theme = ["ananke", "hugo-video"]
resourceDir = "static"

sectionPagesMenu = "main"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
  math = true

  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3
  text_color = "black-80"

  featured_image = ""

ananke_socials = [
    {name = "github", url = "https://github.com/aeyobd"},
    {name = "linkedin", url = "https://www.linkedin.com/in/daniel-boyea-7303b120a/"},
]




[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Research'
    url = '/#research'
    weight = 20

  [[menus.main]]
    name = 'CV'
    url = '/#cv'
    weight= 20

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 25
